# fly.toml app configuration file generated for windsurf-project on 2025-01-31T21:16:25-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'windsurf-project'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
app = "ralpos"
primary_region = "gdl"  # Guadalajara region for better latency in Mexico

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "8000"
  MAX_WORKERS = "2"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[metrics]
  port = 9091
  path = "/metrics"
