AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal Test Lambda Function

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./minimal_lambda
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: GET
