"""Add global invoice relationship

Revision ID: 7794d42f4a57
Revises: 
Create Date: 2025-02-03 18:47:59.662387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7794d42f4a57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_invoice', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('cfdi_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('xml_content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('products',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('is_invoiced')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_invoiced', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('products',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoiced')

    with op.batch_alter_table('global_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('xml_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('cfdi_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
