"""Add payment fields to Sale model

Revision ID: 991355fab46b
Revises: 
Create Date: 2025-02-06 14:25:38.176091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991355fab46b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_received', sa.Float(), server_default=sa.text('0.0'), nullable=False))
        batch_op.add_column(sa.Column('change_amount', sa.Float(), server_default=sa.text('0.0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('change_amount')
        batch_op.drop_column('amount_received')

    # ### end Alembic commands ###
