"""Add folio to GlobalInvoice

Revision ID: 9aa4bc2059b6
Revises: 7794d42f4a57
Create Date: 2025-02-04 17:48:29.818008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa4bc2059b6'
down_revision = '7794d42f4a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_invoice', schema=None) as batch_op:
        batch_op.drop_column('folio')

    # ### end Alembic commands ###
